### ISSUE TITLE
Notifications of questions answered and replies accepted/rejected. 

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#122]
The user will be notified when their question is answered or if their reply is accepted/rejected.

Story points: 2,
Priority: Medium
Risk: Low

- [x] Reply accepted/rejected notification. 2 points. [#133]

**Comment by dfeokti** [comment]
Reopened for acceptance testing.

**Comment by PWatine** [comment]
![122](https://user-images.githubusercontent.com/35372462/37805922-6bfba360-2e13-11e8-8edf-4d3d0b348d27.png)
Test completed.

**Comment by dfeokti** [comment]
User story closed as test are concluded. The user can get notifications for accepted and rejected answers, clear them, and receive new ones.
