### ISSUE TITLE
User ranking page. 

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#124]
**Story points: 3,
Priority: Medium,
Risk: Low**

This recruiter user will be able to navigate to a page with user rankings, based on registration date, tagged languages and amount of accepted answers. 

- [x] User ranking page, sortable by criteria such as registration date or languages. [#135]

**Comment by PWatine** [comment]
![124](https://user-images.githubusercontent.com/35372462/38746689-3d7f2034-3f16-11e8-8f41-d09045fa35a8.png)
Test completed.

**Comment by PWatine** [comment]
![124](https://user-images.githubusercontent.com/35372462/38782480-2b039f0e-40c2-11e8-9192-81c9341ecced.png)
Test completed.

**Comment by dfeokti** [comment]
Acceptance testing passed, user story closed.
