### ISSUE TITLE
Tag implementation

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#127]
**Story points: 6
Priority: High,
Risk: Medium**

The user will have access to persistent keywords on questions, answers, user profile, and job page.

- [x] Question and user profile schema refinement to include keywords. 3 points. [#136]
- [x] Create queries to access and filter keywords, to populate pages requiring the queries. 3 points. [#137]

**Comment by PWatine** [comment]
![127](https://user-images.githubusercontent.com/35372462/38748297-a99452c6-3f1b-11e8-9617-a78145a36b4a.png)
Test complete.

**Comment by dfeokti** [comment]
Closed, passed acceptance testing above.
