### ISSUE TITLE
Multiple types of accounts (user, admin, company)

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#128]
There will be multiple user accounts with different permissions. Admin account will have full control over the website, recruiter will have access to user rankings, moderator will able to edit posts and user has basic functionality only. 

Story points: 6,
Priority: Low,
Risk: High

- [x] Back-end schema refinement to include account types and their permissions. [#138]
- [x] Site-wide functions to support new permissions such as recruiter account creation, and job posting. [#139]

**Comment by dfeokti** [comment]
Moderator will not be implemented.

**Comment by PWatine** [comment]
![128](https://user-images.githubusercontent.com/35372462/37750321-c2bc1b46-2d62-11e8-8f71-2f021daba3e2.png)
Test completed

**Comment by dfeokti** [comment]
Acceptance tests passe,d issue can be closed.
