### ISSUE TITLE
Tag query creation. [#127]

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#137]
**Task, 4 hours**
[User story #127]
Creating queries to pull tags from the user schema and the question schema to populate respective pages.

**Comment by dfeokti** [comment]
Back-end queries completed, to be linked with front-end handlebars.

**Comment by PWatine** [comment]
![127](https://user-images.githubusercontent.com/35372462/37809099-10d12fb2-2e24-11e8-81b7-caf1b8e71f78.png)
Test completed.
