### ISSUE TITLE
Job posting page. [#123]

### ISSUE THREAD

**Issue by BarsemianGeorgik** [Software-Process/Software-Process.github.io#151]
**Task, 2 hours**
User story: #123
Related to task #138, #139 (User story #128)
This page should allow companies to post jobs onto the job listing page with the:
- Name of the job
- Name of the company
- Date posted
- A link to a description of the job

**Comment by kjanei** [comment]
Updated task; following meeting with customer, it is clear that the website must not link to an external page but instead link to a page on this website where the description of the job (along with title, date, company, etc.) can be viewed.
Until this is implemented, this task cannot be closed.

**Comment by dfeokti** [comment]
Users can see a job posting page, created jobs appear in the list.
