### ISSUE TITLE
Bug: Writing a question with tags does not increment the tag values from the user page [#127]

### ISSUE THREAD

**Issue by PWatine** [Software-Process/Software-Process.github.io#188]
Steps:

1. Log into an user account.
2. Go to the user page and remember the values of 3 tags (tested on PHP, Pearl and Lisp).
3. Submit a question with those tags.
4. Go to the user page and look at the values of the 3 tags.
  Expected result: The values of the tags should be incremented by 1.
  Observed result: The values of the tags remain unchanged.

**Comment by vineetkoppalkar** [comment]
@PWatine 
A user's tag score does not increment when they submit a question. They increment when a user's reply is accepted by the author of the question. 

Consider the following scenario, if user A posts a question with the tags PHP and HTML and user B replies to the question, user B's PHP and HTML tag scores will only increase if user A accepts the reply of user B.

**Comment by PWatine** [comment]
Bug is to be closed.
