### ISSUE TITLE
Create basic front page

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#23]
This user story involves creating a simple version of the front page with minimal functionality. Though certain things such as styling may not be final, the aim is to complete the following tasks:

- Lay out the page and its contents (HTML) (0.5 points)
- Apply a basic styling to the page (CSS/Bootstrap) (1 point)
- Incorporate a common header and footer (see #26) (0.5 points)

Key features of this page include:
- A large welcome banner (see `jumbotron` from Bootstrap)
- A vertically-stacked list of questions, providing the ability to see the question's score and title.

This user story in total is worth 2 points.

**Comment by kjanei** [comment]
Fulfilled by pull request #38

**Comment by BarsemianGeorgik** [comment]
![2](https://user-images.githubusercontent.com/22305559/37075264-fef22fe4-219e-11e8-8ff8-527b58c03636.PNG)
