### ISSUE TITLE
Create basic question prompt page

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#24]
This user story involves creating a simple version of the ask-a-question page with minimal functionality. Though certain things such as styling may not be final, the aim is to complete the following tasks:

- Lay out the page and its contents (HTML) (0.5 points)
- Apply a basic styling to the page (CSS/Bootstrap) (1 point)
- Incorporate a common header and footer (see #26 ) (0.5 points)

Key features of this page include:
- A prompt to write a question, specifying any limitation (ex. maximum length)
- A text field within which the user may write a question
- "Ask" and "Cancel" buttons. The buttons need not be functional yet.

This user story in total is worth 2 points.

**Comment by PWatine** [comment]
You may look at this... @kjanei 
I think I accidentally combined both of our parts... Sorry for that.
On the bright side, the buttons are not implemented and there are no text editor contents (like bold or italic buttons) included. 
`<div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <form action="_______" method="post" class="w3-container w3-padding">
              <h6 class="w3-opacity">Ask a question here:</h6>
              <input type="text" name="question" class="w3-opacity" size="74">
              <h6 class="w3-opacity">Enter description here:</h6>
              <p contenteditable="true" class="w3-border w3-padding"></p>
              <button type="button" class="w3-button w3-theme"><i class="fa fa-pencil"></i>  Ask the question</button> 
            </form>
          </div>
        </div>
      </div>`

**Comment by kjanei** [comment]
Resolved by pull request #40

**Comment by BarsemianGeorgik** [comment]
![3](https://user-images.githubusercontent.com/22305559/37075505-1a1c2314-21a0-11e8-9065-66b2663a8dff.PNG)
