### ISSUE TITLE
Create basic question view page

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#25]
This user story involves creating a simple version of the ask-a-question page with minimal functionality. Though certain things such as styling may not be final, the aim is to complete the following tasks:

- Lay out the page and its contents (HTML) (0.5 points)
- Apply a basic styling to the page (CSS/Bootstrap) (1 point)
- Incorporate a common header and footer (see #26 ) (0.5 points)

Key features of this page include:

- The ability to  read a question's title and contents
- Along the left side, the question's score and buttons to upvote(red)/downvote(blue) the question are displayed.
- A text field within which the user may type a reply (does not need to show as comment/reply yet), along with "Reply" and "Delete" buttons. The buttons need not be functional yet.

This user story in total is worth 2 points.

**Comment by PWatine** [comment]
I already have done a simple version of it to view the question in the list of the search result. As for the question with the replies and the buttons itself, I will be doing that today.

**Comment by PWatine** [comment]
New version ready to be reviewed

**Comment by kjanei** [comment]
Task carried over into Sprint 2 due to requested changes.

**Comment by dfeokti** [comment]
New issue opened for Sprint 2, with updated tasks.

**Comment by BarsemianGeorgik** [comment]
![image](https://user-images.githubusercontent.com/22305559/37075998-746903b2-21a2-11e8-9d89-3498a2fca9d1.png)
