### ISSUE TITLE
Create common header and footer for all pages

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#26]
This user story involves creating a header and footer common to all pages. Though certain things such as styling may not be final, the aim is to complete the following tasks:

- Create header with nav bar via Bootstrap (1 point)
- Create footer via Bootstrap (1 point)

The header and footer can be tested on any of the pages being constructed (see #23 #24 #25) to verify its functionality.

This user story in total is worth 2 points.

**Comment by Michael-Gagnon** [comment]
Instructions on how to use w3-inlcude-html:
 [https://www.w3schools.com/howto/howto_html_include.asp](url)

**Comment by kjanei** [comment]
Resolved by pull request #29 .

**Comment by BarsemianGeorgik** [comment]
![image](https://user-images.githubusercontent.com/22305559/37076327-29fdd274-21a4-11e8-9e32-cf0463dde938.png)
