### ISSUE TITLE
Index page implementation.

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#42]
This user will be provided with a list of questions, which will link to individual detailed pages. The user will also see the current score of each of the questions. The page will also include a list of currently popular questions.

**Story points: 2, 
Priority: Medium, 
Risk: Low**

- [x] List of questions as links, 3.5 hours. [#56]
- [x] Sorting list by score, 1.5 hours. [#57]

**Comment by BarsemianGeorgik** [comment]
![image](https://user-images.githubusercontent.com/22305559/37111701-5b34390e-220e-11e8-802d-8eea2903fdcf.png)
