### ISSUE TITLE
Back-end functionality implementation.

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#44]
This user story involves creating and implementing the back-end framework that will support the core features, as well as writing the queries to manipulate the database. 

**Story points: 6, 
Priority: High, 
Risk: Low**

- [x] Implement Express (Node.js framework, used for mongoDB database connection and Handlebars template language.) 2 points, @dfeokti.
- [x] Implement find queries from the database related to the index page. 1 point, @vineetkoppalkar 
- [x] Implement insert queries to the database, (add a new question), with feedback and proper formatting. 1 points, @Mstc08 
- [x] Refine collections in the database (Structure: id, votes, title, author, data...) 1 point, 
@vineetkoppalkar 
- [x] Populating individual question page with data from database. 1 point, @BarsemianGeorgik

**Comment by BarsemianGeorgik** [comment]
@Mstc08  When you add the mongodb module make sure to also add its mongoose module as well!

**Comment by dfeokti** [comment]
The user is able to see data persisting between page reloads and site visits, such as new questions, answers and scores.

**Comment by BarsemianGeorgik** [comment]
![image](https://user-images.githubusercontent.com/22305559/37112492-9d222ab8-2210-11e8-9781-4fbbab4c8ee5.png)
