### ISSUE TITLE
Ask a question page

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#48]
This user will be provided with a page containing text fields that can be used to submit a question. Once the question is submitted, the user will receive feedback that the post has been successfully submitted. 

Story points: 2,
Priority: Low,
Risk: Low

- [x] Ability to submit a question, 1 point.
- [x] Feedback related to the submission, 1 point.

**Comment by dfeokti** [comment]
The user is able to access the page, submit a question, and view it on the index page.

**Comment by PWatine** [comment]
The test has been done. Although, it may be advisable to take care of the possibility that the user does not fill all the textboxes (it currently just creates an error).
![48](https://user-images.githubusercontent.com/35372462/37116779-3c381f3e-221d-11e8-9ca4-16757fe06b60.png)
