### ISSUE TITLE
Create list of questions as links [#42]

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#56]
**Task, 3.5 hours. References [#42].**
On the front page, create a list of questions as links where each question is displayed on one row.
Each row should contain the question's title as a clickable link, author, score, and relative date (ex. "4 hours ago".)

**Comment by vineetkoppalkar** [comment]
In the database, each question has the following properties:
```
(This is an example of one question in the database)
[
	{
		"id" : "53H27RH723HDH29",
		"title" : "How to make a website?",
		"text" : "I would like to use Express and MongoDB to make a website",
		"nbOfVotes" : 0,
		"nbOfAnswers" 1,
		"author" : "John Doe",
		"date" : 10/02/2018 13:26:01 
	}
]
```
For each clickable question link on the index page, we would only need to use title, nbOfVotes, nbOfAnswers, author and date. Would it be possible to style the link as:
![image](https://user-images.githubusercontent.com/22140953/36065906-f7e0ff16-0e6e-11e8-90e5-342651986b6d.png)
where the entire row is a clickable button that redirects the user to the individual question page using the id of the question.

In the index page, it would look something like
![image](https://user-images.githubusercontent.com/22140953/36065940-58aaf09a-0e6f-11e8-9f5f-5bf324588af1.png)
