### ISSUE TITLE
Implement acceptance/rejection of answers [#45]

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#59]
**Task, 1 hour. References user story #45. **
Allow the user to accept or reject answers. 
Note that for now, no permissions system is required; the buttons can be accessible to everyone viewing the page. When the login system is implemented in Sprint 3, this action will have to be restricted to only the asker of the question.

**Comment by dfeokti** [comment]
Acceptance and rejection front-end completed, to be reopened Sprint 3.
