### ISSUE TITLE
Implement voting on questions [#45, #60]

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#61]
**Task, 1 hour. References user story #45, task #60.**
Allow the user to either upvote or downvote a question (but not both.) 
Upvoting a question increases its score from the original by 1, whereas downvoting decreases its score from the original by 1.
The upvote/downvote buttons should be buttons with an appearance similar to upward/downward facing arrows that become coloured when hovered or clicked, and when clicked, update the score of the question that was voted on.
Requires the implementation of task #60.

**Comment by dfeokti** [comment]
Users are able to vote on questions and have the score persist when returning to the page.
