### ISSUE TITLE
Create login/register page [#46]

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#62]
**Task, 3 hours. References user story #46.**
Create and lay out the login/register page.
This page is to be laid out within a central container, which includes:
- A prompt to log in (fields for username and password, and "log in" button) on the left side of the container.
- A prompt to register for the site (fields for desired username and password, and "register" button) on the right side of the container.

All password fields should hide the password being entered.
Note that the functionality for actually logging in or registering will be completed in Sprint 3, when the login system is implemented.

**Comment by PWatine** [comment]
#79

**Comment by dfeokti** [comment]
Front-end of the login page implemented.
