### ISSUE TITLE
Implement question submission [#48]

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#64]
**Task, 2.5 hours. References user story #48.**
Implement the functionality for questions to be submitted - that is, when the user clicks the "Ask" button, the question title and body as well as information about the author, and date of submission is sent to the backend, which adds it to the database.

**Comment by vineetkoppalkar** [comment]
Could you add a field for the author name. Also would it be possible to ensure that the user cannot click submit unless all fields are filled out.

**Comment by dfeokti** [comment]
Working as intended, questions saved to database and can be accessed.
