### ISSUE TITLE
Implement feedback from question submission [#48, #64]

### ISSUE THREAD

**Issue by kjanei** [Software-Process/Software-Process.github.io#65]
**Task, 1.5 hours. References user story #48, task #64. **
This task requires the implementation of task #64. 
Once the database receives the user's question, a response is to shown to the user, locking the question submission field and informing them that the submission was successful.
If for any reason the submission was not successful, the user should also be informed of this fact.

**Comment by dfeokti** [comment]
Users are redirected to the individual question page upon submission.
