### ISSUE TITLE
Back-end registration page functionality. 

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#86]
**Story points: 1,
Priority: Medium,
Risk: Low**

The user will be able to choose a user name and password, and have them stored in the database to log in in the future.

- [x] Ability to enter a user name and password to be  stored on the server., 2 hours. {#95]
- [x] Registration feedback and creation of profile. 1 hour [#96]

**Comment by PWatine** [comment]
The test case for this issue has been made.

**Comment by PWatine** [comment]
![86](https://user-images.githubusercontent.com/35372462/37132453-cd8ab350-225b-11e8-96b5-3764ad671a37.png)
Test completed.

**Comment by dfeokti** [comment]
All tests passed, the user is able to register.
